<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { Card, Button, Badge, Spinner, Input } from '@/components/common';
import FormField from '@/components/config/FormField.vue';
import { useConfigStore } from '@/stores';
import { useTestConnection, useSaveConfig } from '@/api';
import { useToast } from '@/composables';

const emit = defineEmits<{
  (e: 'complete'): void;
  (e: 'skip'): void;
}>();

const toast = useToast();
const configStore = useConfigStore();

// Wizard state
const currentStep = ref(1);
const totalSteps = 4;

// Form data
const plexUrl = ref('');
const plexToken = ref('');
const tmdbApiKey = ref('');
const selectedLibraries = ref<string[]>([]);

// Connection test results
const plexTested = ref(false);
const plexConnected = ref(false);
const plexLibraries = ref<Array<{ key: string; title: string; type: string }>>([]);
const tmdbTested = ref(false);
const tmdbConnected = ref(false);

// Loading states
const testingPlex = ref(false);
const testingTmdb = ref(false);
const saving = ref(false);

// API hooks
const testConnectionMutation = useTestConnection();
const saveConfigMutation = useSaveConfig();

// Steps configuration
const steps = [
  { number: 1, title: 'Welcome', description: 'Introduction to Kometa' },
  { number: 2, title: 'Plex Server', description: 'Connect your Plex server' },
  { number: 3, title: 'TMDb API', description: 'Get movie & TV metadata' },
  { number: 4, title: 'Libraries', description: 'Select libraries to manage' },
];

// Progress percentage
const progress = computed(() => ((currentStep.value - 1) / (totalSteps - 1)) * 100);

// Can proceed to next step
const canProceed = computed(() => {
  switch (currentStep.value) {
    case 1:
      return true;
    case 2:
      return plexConnected.value;
    case 3:
      return tmdbConnected.value;
    case 4:
      return selectedLibraries.value.length > 0;
    default:
      return false;
  }
});

// Test Plex connection
async function testPlex() {
  if (!plexUrl.value || !plexToken.value) {
    toast.warning('Please enter both Plex URL and token');
    return;
  }

  testingPlex.value = true;
  plexTested.value = false;

  try {
    const result = await testConnectionMutation.mutateAsync({
      service: 'plex',
      config: {
        url: plexUrl.value,
        token: plexToken.value,
      },
    });

    plexTested.value = true;
    plexConnected.value = result.success;

    if (result.success) {
      toast.success('Plex connection successful!');
      // Get libraries from the response
      if (result.libraries) {
        plexLibraries.value = result.libraries;
      }
    } else {
      toast.error(result.error || 'Failed to connect to Plex');
    }
  } catch (err) {
    plexTested.value = true;
    plexConnected.value = false;
    toast.error('Failed to test Plex connection');
  } finally {
    testingPlex.value = false;
  }
}

// Test TMDb connection
async function testTmdb() {
  if (!tmdbApiKey.value) {
    toast.warning('Please enter your TMDb API key');
    return;
  }

  testingTmdb.value = true;
  tmdbTested.value = false;

  try {
    const result = await testConnectionMutation.mutateAsync({
      service: 'tmdb',
      config: {
        apikey: tmdbApiKey.value,
      },
    });

    tmdbTested.value = true;
    tmdbConnected.value = result.success;

    if (result.success) {
      toast.success('TMDb API key is valid!');
    } else {
      toast.error(result.error || 'Invalid TMDb API key');
    }
  } catch (err) {
    tmdbTested.value = true;
    tmdbConnected.value = false;
    toast.error('Failed to test TMDb connection');
  } finally {
    testingTmdb.value = false;
  }
}

// Toggle library selection
function toggleLibrary(key: string) {
  const idx = selectedLibraries.value.indexOf(key);
  if (idx >= 0) {
    selectedLibraries.value.splice(idx, 1);
  } else {
    selectedLibraries.value.push(key);
  }
}

// Generate and save config
async function completeSetup() {
  saving.value = true;

  try {
    // Build minimal config YAML
    const librariesYaml = selectedLibraries.value
      .map((key) => {
        const lib = plexLibraries.value.find((l) => l.key === key);
        return `  ${lib?.title || key}:\n    collection_files:\n      - default: basic`;
      })
      .join('\n');

    const configYaml = `# Kometa Configuration
# Generated by Setup Wizard

plex:
  url: ${plexUrl.value}
  token: ${plexToken.value}

tmdb:
  apikey: ${tmdbApiKey.value}
  language: en
  region: US

libraries:
${librariesYaml}

settings:
  run_order:
    - operations
    - metadata
    - collections
    - overlays
`;

    await saveConfigMutation.mutateAsync(configYaml);
    configStore.setRawConfig(configYaml, false);
    configStore.markSaved();

    toast.success('Configuration saved successfully!');
    emit('complete');
  } catch (err) {
    toast.error('Failed to save configuration');
  } finally {
    saving.value = false;
  }
}

// Navigation
function nextStep() {
  if (currentStep.value < totalSteps) {
    currentStep.value++;
  }
}

function prevStep() {
  if (currentStep.value > 1) {
    currentStep.value--;
  }
}
</script>

<template>
  <div class="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
    <Card class="w-full max-w-2xl max-h-[90vh] overflow-auto">
      <!-- Header -->
      <template #header>
        <div class="flex items-center justify-between w-full">
          <div class="flex items-center gap-3">
            <div class="w-10 h-10 rounded-full bg-kometa-gold/20 flex items-center justify-center">
              <svg class="w-6 h-6 text-kometa-gold" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>
              </svg>
            </div>
            <div>
              <h2 class="text-lg font-semibold">Setup Wizard</h2>
              <p class="text-sm text-content-secondary">Step {{ currentStep }} of {{ totalSteps }}</p>
            </div>
          </div>
          <Button variant="ghost" size="sm" @click="emit('skip')">
            Skip Setup
          </Button>
        </div>
      </template>

      <!-- Progress bar -->
      <div class="mb-6">
        <div class="flex justify-between mb-2">
          <span
            v-for="step in steps"
            :key="step.number"
            class="text-xs font-medium"
            :class="step.number <= currentStep ? 'text-kometa-gold' : 'text-content-muted'"
          >
            {{ step.title }}
          </span>
        </div>
        <div class="h-2 bg-surface-tertiary rounded-full overflow-hidden">
          <div
            class="h-full bg-kometa-gold transition-all duration-300"
            :style="{ width: `${progress}%` }"
          />
        </div>
      </div>

      <!-- Step Content -->
      <div class="min-h-[300px]">
        <!-- Step 1: Welcome -->
        <div v-if="currentStep === 1" class="space-y-4">
          <div class="text-center py-6">
            <div class="w-20 h-20 mx-auto mb-4 rounded-full bg-kometa-gold/20 flex items-center justify-center">
              <svg class="w-10 h-10 text-kometa-gold" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
              </svg>
            </div>
            <h3 class="text-xl font-semibold mb-2">Welcome to Kometa!</h3>
            <p class="text-content-secondary max-w-md mx-auto">
              Kometa automatically creates and manages collections, overlays, and metadata for your Plex media library.
            </p>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div class="p-4 rounded-lg bg-surface-tertiary text-center">
              <div class="text-2xl mb-2">&#128218;</div>
              <h4 class="font-medium text-sm">Collections</h4>
              <p class="text-xs text-content-secondary mt-1">Auto-create themed collections</p>
            </div>
            <div class="p-4 rounded-lg bg-surface-tertiary text-center">
              <div class="text-2xl mb-2">&#127912;</div>
              <h4 class="font-medium text-sm">Overlays</h4>
              <p class="text-xs text-content-secondary mt-1">Add visual badges to posters</p>
            </div>
            <div class="p-4 rounded-lg bg-surface-tertiary text-center">
              <div class="text-2xl mb-2">&#128196;</div>
              <h4 class="font-medium text-sm">Metadata</h4>
              <p class="text-xs text-content-secondary mt-1">Enhance titles & descriptions</p>
            </div>
          </div>

          <div class="p-4 rounded-lg bg-info/10 border border-info/20">
            <p class="text-sm">
              <strong>What you'll need:</strong>
            </p>
            <ul class="text-sm text-content-secondary mt-2 space-y-1 list-disc list-inside">
              <li>Your Plex server URL and authentication token</li>
              <li>A free TMDb API key (we'll show you how to get one)</li>
            </ul>
          </div>
        </div>

        <!-- Step 2: Plex -->
        <div v-if="currentStep === 2" class="space-y-4">
          <div>
            <h3 class="text-lg font-semibold mb-1">Connect Your Plex Server</h3>
            <p class="text-sm text-content-secondary">
              Enter your Plex server URL and authentication token.
            </p>
          </div>

          <FormField
            label="Plex URL"
            required
            tooltip="The direct URL to your Plex server (not app.plex.tv)"
          >
            <Input
              v-model="plexUrl"
              placeholder="http://192.168.1.100:32400"
              @keyup.enter="testPlex"
            />
            <template #help>
              Example: http://your-server-ip:32400 or https://plex.yourdomain.com
            </template>
          </FormField>

          <FormField
            label="Plex Token"
            required
            tooltip="Your X-Plex-Token for authentication"
          >
            <Input
              v-model="plexToken"
              type="password"
              placeholder="Your Plex token"
              @keyup.enter="testPlex"
            />
            <template #help>
              <a
                href="https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/"
                target="_blank"
                class="text-kometa-gold hover:underline"
              >
                How to find your Plex token
              </a>
            </template>
          </FormField>

          <div class="flex items-center gap-4 p-4 rounded-lg bg-surface-tertiary">
            <Button
              :disabled="!plexUrl || !plexToken || testingPlex"
              @click="testPlex"
            >
              <Spinner v-if="testingPlex" size="sm" class="mr-2" />
              Test Connection
            </Button>

            <div v-if="plexTested" class="flex items-center gap-2">
              <Badge :variant="plexConnected ? 'success' : 'error'">
                {{ plexConnected ? 'Connected' : 'Failed' }}
              </Badge>
              <span v-if="plexConnected && plexLibraries.length" class="text-sm text-content-secondary">
                Found {{ plexLibraries.length }} libraries
              </span>
            </div>
          </div>
        </div>

        <!-- Step 3: TMDb -->
        <div v-if="currentStep === 3" class="space-y-4">
          <div>
            <h3 class="text-lg font-semibold mb-1">Configure TMDb API</h3>
            <p class="text-sm text-content-secondary">
              TMDb provides metadata, images, and collection information for your media.
            </p>
          </div>

          <div class="p-4 rounded-lg bg-surface-tertiary space-y-3">
            <h4 class="font-medium text-sm">How to get a free TMDb API key:</h4>
            <ol class="text-sm text-content-secondary space-y-2 list-decimal list-inside">
              <li>Go to <a href="https://www.themoviedb.org/signup" target="_blank" class="text-kometa-gold hover:underline">themoviedb.org/signup</a> and create a free account</li>
              <li>Go to <a href="https://www.themoviedb.org/settings/api" target="_blank" class="text-kometa-gold hover:underline">Settings &gt; API</a></li>
              <li>Request an API key (select "Personal use")</li>
              <li>Copy the "API Key (v3 auth)" value</li>
            </ol>
          </div>

          <FormField
            label="TMDb API Key"
            required
            tooltip="Your TMDb API key (v3 auth)"
          >
            <Input
              v-model="tmdbApiKey"
              type="password"
              placeholder="Your TMDb API key"
              @keyup.enter="testTmdb"
            />
          </FormField>

          <div class="flex items-center gap-4 p-4 rounded-lg bg-surface-tertiary">
            <Button
              :disabled="!tmdbApiKey || testingTmdb"
              @click="testTmdb"
            >
              <Spinner v-if="testingTmdb" size="sm" class="mr-2" />
              Test API Key
            </Button>

            <div v-if="tmdbTested" class="flex items-center gap-2">
              <Badge :variant="tmdbConnected ? 'success' : 'error'">
                {{ tmdbConnected ? 'Valid' : 'Invalid' }}
              </Badge>
            </div>
          </div>
        </div>

        <!-- Step 4: Libraries -->
        <div v-if="currentStep === 4" class="space-y-4">
          <div>
            <h3 class="text-lg font-semibold mb-1">Select Libraries</h3>
            <p class="text-sm text-content-secondary">
              Choose which Plex libraries Kometa should manage.
            </p>
          </div>

          <div v-if="plexLibraries.length > 0" class="space-y-2">
            <button
              v-for="lib in plexLibraries"
              :key="lib.key"
              class="w-full flex items-center gap-3 p-4 rounded-lg border-2 transition-colors"
              :class="selectedLibraries.includes(lib.key)
                ? 'border-kometa-gold bg-kometa-gold/10'
                : 'border-border bg-surface-tertiary hover:border-kometa-gold/50'"
              @click="toggleLibrary(lib.key)"
            >
              <div class="w-10 h-10 rounded-full bg-surface-primary flex items-center justify-center">
                <span class="text-lg">{{ lib.type === 'movie' ? '&#127909;' : '&#128250;' }}</span>
              </div>
              <div class="flex-1 text-left">
                <div class="font-medium">{{ lib.title }}</div>
                <div class="text-sm text-content-secondary capitalize">{{ lib.type }} library</div>
              </div>
              <div
                class="w-6 h-6 rounded-full border-2 flex items-center justify-center transition-colors"
                :class="selectedLibraries.includes(lib.key)
                  ? 'border-kometa-gold bg-kometa-gold'
                  : 'border-content-muted'"
              >
                <svg
                  v-if="selectedLibraries.includes(lib.key)"
                  class="w-4 h-4 text-black"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7"/>
                </svg>
              </div>
            </button>
          </div>

          <div v-else class="text-center py-8 text-content-muted">
            <p>No libraries found. Please go back and verify your Plex connection.</p>
          </div>

          <div v-if="selectedLibraries.length > 0" class="p-4 rounded-lg bg-success/10 border border-success/20">
            <p class="text-sm">
              <strong>Ready to go!</strong> Kometa will create a basic configuration for your {{ selectedLibraries.length }} selected {{ selectedLibraries.length === 1 ? 'library' : 'libraries' }}.
            </p>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="flex items-center justify-between mt-6 pt-4 border-t border-border">
        <Button
          v-if="currentStep > 1"
          variant="secondary"
          @click="prevStep"
        >
          Back
        </Button>
        <div v-else />

        <Button
          v-if="currentStep < totalSteps"
          :disabled="!canProceed"
          @click="nextStep"
        >
          Continue
        </Button>
        <Button
          v-else
          :disabled="!canProceed || saving"
          @click="completeSetup"
        >
          <Spinner v-if="saving" size="sm" class="mr-2" />
          Complete Setup
        </Button>
      </div>
    </Card>
  </div>
</template>
